### ISSUE TITLE
golang.org都不好用了，跳转了

### ISSUE THREAD

**Issue by hweidz** [cyfdecyf/cow#278]
试了几次以为是GFW的问题，访问了下跳转到https://godoc.org/golang.org/x/crypto/blowfish了，go get的时候图示找不到blowfish和CAT5

**Comment by cyfdecyf** [comment]
Go 1.4 对 package 的引用有了新的规则，我找时间试下 `go get` 有没有问题。

**Comment by ddatsh** [comment]
就是GFW的问题，没有正确科学上网去 go get

**Comment by CodeFalling** [comment]
`go version go1.4.2 darwin/amd64`，使用`proxychains-ng`挂的`shadowsocks`，`go get`同样不成功.

**Comment by fzerorubigd** [comment]
@CodeFalling Go is not a dynamic build binary, so its never load a network shared library, proxychains is base on injecting a shared library, so its not working with Go, and almost all go binaries. 
But it use the http_proxy and https_proxy from env. 

I hope its related, since I use google translator to read the topics.

**Comment by CodeFalling** [comment]
@fzerorubigd Thanks for pointed out that.Set all_proxy works great.
